version: '2'
services:
    project9-app:
        image: project9
        external_links:
            - project9-mysql:mysql
            - project9-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/project9?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    project9-mysql:
        extends:
            file: mysql.yml
            service: project9-mysql
    project9-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: project9-elasticsearch
