version: '2'
services:
    project9-mysql:
        container_name: project9-mysql
        image: mysql:5.7.13
        # volumes:
        #     - ~/volumes/jhipster/project9/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=project9
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl
